INSERT OR IGNORE INTO variables (id, name, latex, science, branch, topic, difficulty, si_unit, dim_M, dim_L, dim_T, dim_I, dim_Θ, dim_N, dim_J) VALUES
  ('angle',
   '{"en-us": "Plane angle"}',
   '\theta',
   '{"en-us": "Physics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Trigonometry"}',
   1,
   '[{"unit": "radian", "exponent": 1}]',
   0,0,0,0,0,0,0),
  ('solid_angle',
   '{"en-us": "Solid angle"}',
   '\Omega',
   '{"en-us": "Physics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Trigonometry"}',
   2,
   '[{"unit": "steradian", "exponent": 1}]',
   0,0,0,0,0,0,0),
  ('frequency',
   '{"en-us": "Frequency"}',
   'f',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Waves"}',
   2,
   '[{"unit": "hertz", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('power',
   '{"en-us": "Power"}',
   'P',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Energy"}',
   2,
   '[{"unit": "watt", "exponent": 1}]',
   1,2,-3,0,0,0,0),
  ('charge',
   '{"en-us": "Electric charge"}',
   'Q',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   2,
   '[{"unit": "coulomb", "exponent": 1}]',
   0,0,1,1,0,0,0),
  ('electric_potential',
   '{"en-us": "Electric potential"}',
   'V',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "volt", "exponent": 1}]',
   1,2,-3,-1,0,0,0),
  ('conductance',
   '{"en-us": "Electrical conductance"}',
   'G',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "siemens", "exponent": 1}]',
   -1,-2,3,2,0,0,0),
  ('capacitance',
   '{"en-us": "Capacitance"}',
   'C',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "farad", "exponent": 1}]',
   -1,-2,4,2,0,0,0),
  ('inductance',
   '{"en-us": "Inductance"}',
   'L',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "henry", "exponent": 1}]',
   1,2,-2,-2,0,0,0),
  ('magnetic_flux_density',
   '{"en-us": "Magnetic flux density"}',
   'B',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "tesla", "exponent": 1}]',
   1,0,-2,-1,0,0,0),
  ('magnetic_flux',
   '{"en-us": "Magnetic flux"}',
   '\Phi',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "weber", "exponent": 1}]',
   1,2,-2,-1,0,0,0),
  ('luminous_flux',
   '{"en-us": "Luminous flux"}',
   '\Phi_\mathrm{v}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "lumen", "exponent": 1}]',
   0,0,0,0,0,0,1),
  ('illuminance',
   '{"en-us": "Illuminance"}',
   'E_\mathrm{v}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "lux", "exponent": 1}]',
   0,-2,0,0,0,0,1),
  ('activity',
   '{"en-us": "Activity"}',
   'A',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radioactivity"}',
   3,
   '[{"unit": "becquerel", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('absorbed_dose',
   '{"en-us": "Absorbed dose"}',
   'D',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "gray", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('dose_equivalent',
   '{"en-us": "Dose equivalent"}',
   'H',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "sievert", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('catalytic_activity',
   '{"en-us": "Catalytic activity"}',
   'k',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Kinetics"}',
   3,
   '[{"unit": "katal", "exponent": 1}]',
   0,0,-1,0,0,1,0),
  ('area',
   '{"en-us": "Area"}',
   'A',
   '{"en-us": "Mathematics"}',
   '{"en-us": "Geometry"}',
   '{"en-us": "Area"}',
   1,
   '[{"unit": "square_metre", "exponent": 1}]',
   0,2,0,0,0,0,0),
  ('density',
   '{"en-us": "Density"}',
   '\rho',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   2,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   1,-3,0,0,0,0,0),
  ('surface_density',
   '{"en-us": "Surface density"}',
   '\rho_A',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   3,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   1,-2,0,0,0,0,0),
  ('specific_volume',
   '{"en-us": "Specific volume"}',
   'v',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Continuum mechanics"}',
   3,
   '[{"unit": "cubic_metre", "exponent": 1}, {"unit": "kilogram", "exponent": -1}]',
   -1,3,0,0,0,0,0),
  ('current_density',
   '{"en-us": "Current density"}',
   'j',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   3,
   '[{"unit": "ampere", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   0,-2,0,1,0,0,0),
  ('magnetic_field_strength',
   '{"en-us": "Magnetic field strength"}',
   'H',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   3,
   '[{"unit": "ampere", "exponent": 1}, {"unit": "metre", "exponent": -1}]',
   0,-1,0,1,0,0,0),
  ('concentration',
   '{"en-us": "Concentration"}',
   'c',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Solutions"}',
   2,
   '[{"unit": "mole", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   0,-3,0,0,0,1,0),
  ('mass_concentration',
   '{"en-us": "Mass concentration"}',
   '\gamma',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Solutions"}',
   3,
   '[{"unit": "kilogram", "exponent": 1}, {"unit": "cubic_metre", "exponent": -1}]',
   1,-3,0,0,0,0,0),
  ('luminance',
   '{"en-us": "Luminance"}',
   'L_\mathrm{v}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "candela", "exponent": 1}, {"unit": "square_metre", "exponent": -1}]',
   0,-2,0,0,0,0,1),
  ('wavenumber',
   '{"en-us": "Wavenumber"}',
   '\tilde{\nu}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Waves"}',
   3,
   '[{"unit": "reciprocal_metre", "exponent": 1}]',
   0,-1,0,0,0,0,0),
  ('dynamic_viscosity',
   '{"en-us": "Dynamic viscosity"}',
   '\eta',
   '{"en-us": "Physics"}',
   '{"en-us": "Fluid mechanics"}',
   '{"en-us": "Viscosity"}',
   3,
   '[{"unit": "pascal_second", "exponent": 1}]',
   1,-1,-1,0,0,0,0),
  ('torque',
   '{"en-us": "Torque"}',
   '\tau',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "newton_metre", "exponent": 1}]',
   1,2,-2,0,0,0,0),
  ('surface_tension',
   '{"en-us": "Surface tension"}',
   '\gamma',
   '{"en-us": "Physics"}',
   '{"en-us": "Fluid mechanics"}',
   '{"en-us": "Surface phenomena"}',
   3,
   '[{"unit": "newton_per_metre", "exponent": 1}]',
   1,0,-2,0,0,0,0),
  ('angular_velocity',
   '{"en-us": "Angular velocity"}',
   '\omega',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "radian_per_second", "exponent": 1}]',
   0,0,-1,0,0,0,0),
  ('angular_acceleration',
   '{"en-us": "Angular acceleration"}',
   '\alpha',
   '{"en-us": "Physics"}',
   '{"en-us": "Classical mechanics"}',
   '{"en-us": "Rotation"}',
   3,
   '[{"unit": "radian_per_second_sq", "exponent": 1}]',
   0,0,-2,0,0,0,0),
  ('irradiance',
   '{"en-us": "Irradiance"}',
   'E',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   3,
   '[{"unit": "watt_per_square_metre", "exponent": 1}]',
   1,0,-3,0,0,0,0),
  ('entropy',
   '{"en-us": "Entropy"}',
   'S',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Second law"}',
   3,
   '[{"unit": "joule_per_kelvin", "exponent": 1}]',
   1,2,-2,0,-1,0,0),
  ('specific_heat_capacity',
   '{"en-us": "Specific heat capacity"}',
   'c',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Heat transfer"}',
   3,
   '[{"unit": "joule_per_kilogram_kelvin", "exponent": 1}]',
   0,2,-2,0,-1,0,0),
  ('specific_energy',
   '{"en-us": "Specific energy"}',
   'e',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Energy"}',
   3,
   '[{"unit": "joule_per_kilogram", "exponent": 1}]',
   0,2,-2,0,0,0,0),
  ('thermal_conductivity',
   '{"en-us": "Thermal conductivity"}',
   'k',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Heat transfer"}',
   3,
   '[{"unit": "watt_per_metre_kelvin", "exponent": 1}]',
   1,1,-3,0,-1,0,0),
  ('energy_density',
   '{"en-us": "Energy density"}',
   'u',
   '{"en-us": "Physics"}',
   '{"en-us": "Thermodynamics"}',
   '{"en-us": "Energy"}',
   3,
   '[{"unit": "joule_per_cubic_metre", "exponent": 1}]',
   1,-1,-2,0,0,0,0),
  ('electric_field_strength',
   '{"en-us": "Electric field strength"}',
   'E',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "volt_per_metre", "exponent": 1}]',
   1,1,-3,-1,0,0,0),
  ('charge_density',
   '{"en-us": "Electric charge density"}',
   '\rho',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "coulomb_per_cubic_metre", "exponent": 1}]',
   0,-3,1,1,0,0,0),
  ('surface_charge_density',
   '{"en-us": "Surface charge density"}',
   '\sigma',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   3,
   '[{"unit": "coulomb_per_square_metre", "exponent": 1}]',
   0,-2,1,1,0,0,0),
  ('permittivity',
   '{"en-us": "Permittivity"}',
   '\varepsilon',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Electrostatics"}',
   4,
   '[{"unit": "farad_per_metre", "exponent": 1}]',
   -1,-3,4,2,0,0,0),
  ('permeability',
   '{"en-us": "Permeability"}',
   '\mu',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Magnetism"}',
   4,
   '[{"unit": "henry_per_metre", "exponent": 1}]',
   1,1,-2,-2,0,0,0),
  ('molar_energy',
   '{"en-us": "Molar energy"}',
   'E_\mathrm{m}',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Thermochemistry"}',
   3,
   '[{"unit": "joule_per_mole", "exponent": 1}]',
   1,2,-2,0,0,-1,0),
  ('molar_entropy',
   '{"en-us": "Molar entropy"}',
   'S_\mathrm{m}',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Thermochemistry"}',
   3,
   '[{"unit": "joule_per_mole_kelvin", "exponent": 1}]',
   1,2,-2,0,-1,-1,0),
  ('exposure',
   '{"en-us": "Exposure"}',
   'X',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "coulomb_per_kilogram", "exponent": 1}]',
   -1,0,1,1,0,0,0),
  ('absorbed_dose_rate',
   '{"en-us": "Absorbed dose rate"}',
   '\dot{D}',
   '{"en-us": "Physics"}',
   '{"en-us": "Nuclear physics"}',
   '{"en-us": "Radiation"}',
   4,
   '[{"unit": "gray_per_second", "exponent": 1}]',
   0,2,-3,0,0,0,0),
  ('radiant_intensity',
   '{"en-us": "Radiant intensity"}',
   'I_\mathrm{e}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   4,
   '[{"unit": "watt_per_steradian", "exponent": 1}]',
   1,2,-3,0,0,0,0),
  ('radiance',
   '{"en-us": "Radiance"}',
   'L_\mathrm{e}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Radiometry"}',
   4,
   '[{"unit": "watt_per_square_metre_steradian", "exponent": 1}]',
   1,0,-3,0,0,0,0),
  ('catalytic_activity_concentration',
   '{"en-us": "Catalytic activity concentration"}',
   'k_\mathrm{v}',
   '{"en-us": "Chemistry"}',
   '{"en-us": "Physical chemistry"}',
   '{"en-us": "Kinetics"}',
   4,
   '[{"unit": "katal_per_cubic_metre", "exponent": 1}]',
   0,-3,-1,0,0,1,0),
  ('electric_current',
   '{"en-us": "Electric current"}',
   'I',
   '{"en-us": "Physics"}',
   '{"en-us": "Electromagnetism"}',
   '{"en-us": "Circuits"}',
   2,
   '[{"unit": "ampere", "exponent": 1}]',
   0,0,0,1,0,0,0),
  ('luminous_intensity',
   '{"en-us": "Luminous intensity"}',
   'I_\mathrm{v}',
   '{"en-us": "Physics"}',
   '{"en-us": "Optics"}',
   '{"en-us": "Photometry"}',
   3,
   '[{"unit": "candela", "exponent": 1}]',
   0,0,0,0,0,0,1)
;

-- ============================================================
-- New units
-- ============================================================
INSERT OR IGNORE INTO units (id, variable_id, symbol, name, factor_to_si, offset, si_unit, unit_system) VALUES
  ('ampere', 'electric_current', '\mathrm{A}', '{"en-us": "Ampere"}',
   1, 0, 1, 'SI'),
  ('mole', 'amount', '\mathrm{mol}', '{"en-us": "Mole"}',
   1, 0, 1, 'SI'),
  ('candela', 'luminous_intensity', '\mathrm{cd}', '{"en-us": "Candela"}',
   1, 0, 1, 'SI'),
  ('radian', 'angle', '\mathrm{rad}', '{"en-us": "Radian"}',
   1, 0, 1, 'SI'),
  ('steradian', 'solid_angle', '\mathrm{sr}', '{"en-us": "Steradian"}',
   1, 0, 1, 'SI'),
  ('hertz', 'frequency', '\mathrm{Hz}', '{"en-us": "Hertz"}',
   1, 0, 1, 'SI'),
  ('pascal', 'pressure', '\mathrm{Pa}', '{"en-us": "Pascal"}',
   1, 0, 1, 'SI'),
  ('joule', 'energy', '\mathrm{J}', '{"en-us": "Joule"}',
   1, 0, 1, 'SI'),
  ('watt', 'power', '\mathrm{W}', '{"en-us": "Watt"}',
   1, 0, 1, 'SI'),
  ('coulomb', 'charge', '\mathrm{C}', '{"en-us": "Coulomb"}',
   1, 0, 1, 'SI'),
  ('volt', 'electric_potential', '\mathrm{V}', '{"en-us": "Volt"}',
   1, 0, 1, 'SI'),
  ('siemens', 'conductance', '\mathrm{S}', '{"en-us": "Siemens"}',
   1, 0, 1, 'SI'),
  ('farad', 'capacitance', '\mathrm{F}', '{"en-us": "Farad"}',
   1, 0, 1, 'SI'),
  ('henry', 'inductance', '\mathrm{H}', '{"en-us": "Henry"}',
   1, 0, 1, 'SI'),
  ('tesla', 'magnetic_flux_density', '\mathrm{T}', '{"en-us": "Tesla"}',
   1, 0, 1, 'SI'),
  ('weber', 'magnetic_flux', '\mathrm{Wb}', '{"en-us": "Weber"}',
   1, 0, 1, 'SI'),
  ('lumen', 'luminous_flux', '\mathrm{lm}', '{"en-us": "Lumen"}',
   1, 0, 1, 'SI'),
  ('lux', 'illuminance', '\mathrm{lx}', '{"en-us": "Lux"}',
   1, 0, 1, 'SI'),
  ('becquerel', 'activity', '\mathrm{Bq}', '{"en-us": "Becquerel"}',
   1, 0, 1, 'SI'),
  ('gray', 'absorbed_dose', '\mathrm{Gy}', '{"en-us": "Gray"}',
   1, 0, 1, 'SI'),
  ('sievert', 'dose_equivalent', '\mathrm{Sv}', '{"en-us": "Sievert"}',
   1, 0, 1, 'SI'),
  ('katal', 'catalytic_activity', '\mathrm{kat}', '{"en-us": "Katal"}',
   1, 0, 1, 'SI'),
  ('square_metre', 'area', '\mathrm{m}^{2}', '{"en-us": "Square meter", "en-uk": "Square metre"}',
   1, 0, 1, 'SI'),
  ('cubic_metre', 'volume', '\mathrm{m}^{3}', '{"en-us": "Cubic meter", "en-uk": "Cubic metre"}',
   1, 0, 1, 'SI'),
  ('metre_per_second', 'velocity', '\mathrm{m}/\mathrm{s}', '{"en-us": "Meter per second", "en-uk": "Metre per second"}',
   1, 0, 1, 'SI'),
  ('metre_per_second_sq', 'acceleration', '\mathrm{m}/\mathrm{s}^{2}', '{"en-us": "Meter per second squared", "en-uk": "Metre per second squared"}',
   1, 0, 1, 'SI'),
  ('reciprocal_metre', 'wavenumber', '\mathrm{m}^{-1}', '{"en-us": "Reciprocal meter", "en-uk": "Reciprocal metre"}',
   1, 0, 1, 'SI'),
  ('kilogram_per_cubic_metre', 'density', '\mathrm{kg}/\mathrm{m}^{3}', '{"en-us": "Kilogram per cubic meter", "en-uk": "Kilogram per cubic metre"}',
   1, 0, 1, 'SI'),
  ('kilogram_per_square_metre', 'surface_density', '\mathrm{kg}/\mathrm{m}^{2}', '{"en-us": "Kilogram per square meter", "en-uk": "Kilogram per square metre"}',
   1, 0, 1, 'SI'),
  ('cubic_metre_per_kilogram', 'specific_volume', '\mathrm{m}^{3}/\mathrm{kg}', '{"en-us": "Cubic meter per kilogram", "en-uk": "Cubic metre per kilogram"}',
   1, 0, 1, 'SI'),
  ('ampere_per_square_metre', 'current_density', '\mathrm{A}/\mathrm{m}^{2}', '{"en-us": "Ampere per square meter", "en-uk": "Ampere per square metre"}',
   1, 0, 1, 'SI'),
  ('ampere_per_metre', 'magnetic_field_strength', '\mathrm{A}/\mathrm{m}', '{"en-us": "Ampere per meter", "en-uk": "Ampere per metre"}',
   1, 0, 1, 'SI'),
  ('mole_per_cubic_metre', 'concentration', '\mathrm{mol}/\mathrm{m}^{3}', '{"en-us": "Mole per cubic meter", "en-uk": "Mole per cubic metre"}',
   1, 0, 1, 'SI'),
  ('kilogram_per_cubic_metre_mass', 'mass_concentration', '\mathrm{kg}/\mathrm{m}^{3}', '{"en-us": "Kilogram per cubic meter", "en-uk": "Kilogram per cubic metre"}',
   1, 0, 1, 'SI'),
  ('candela_per_square_metre', 'luminance', '\mathrm{cd}/\mathrm{m}^{2}', '{"en-us": "Candela per square meter", "en-uk": "Candela per square metre"}',
   1, 0, 1, 'SI'),
  ('pascal_second', 'dynamic_viscosity', '\mathrm{Pa}\cdot\mathrm{s}', '{"en-us": "Pascal-second"}',
   1, 0, 1, 'SI'),
  ('newton_metre', 'torque', '\mathrm{N}\cdot\mathrm{m}', '{"en-us": "Newton-metre"}',
   1, 0, 1, 'SI'),
  ('newton_per_metre', 'surface_tension', '\mathrm{N}/\mathrm{m}', '{"en-us": "Newton per meter", "en-uk": "Newton per metre"}',
   1, 0, 1, 'SI'),
  ('radian_per_second', 'angular_velocity', '\mathrm{rad}/\mathrm{s}', '{"en-us": "Radian per second"}',
   1, 0, 1, 'SI'),
  ('radian_per_second_sq', 'angular_acceleration', '\mathrm{rad}/\mathrm{s}^{2}', '{"en-us": "Radian per second squared"}',
   1, 0, 1, 'SI'),
  ('watt_per_square_metre', 'irradiance', '\mathrm{W}/\mathrm{m}^{2}', '{"en-us": "Watt per square meter", "en-uk": "Watt per square metre"}',
   1, 0, 1, 'SI'),
  ('joule_per_kelvin', 'entropy', '\mathrm{J}/\mathrm{K}', '{"en-us": "Joule per kelvin"}',
   1, 0, 1, 'SI'),
  ('joule_per_kilogram_kelvin', 'specific_heat_capacity', '\mathrm{J}/(\mathrm{kg}\cdot\mathrm{K})', '{"en-us": "Joule per kilogram-kelvin"}',
   1, 0, 1, 'SI'),
  ('joule_per_kilogram', 'specific_energy', '\mathrm{J}/\mathrm{kg}', '{"en-us": "Joule per kilogram"}',
   1, 0, 1, 'SI'),
  ('watt_per_metre_kelvin', 'thermal_conductivity', '\mathrm{W}/(\mathrm{m}\cdot\mathrm{K})', '{"en-us": "Watt per meter-kelvin", "en-uk": "Watt per metre-kelvin"}',
   1, 0, 1, 'SI'),
  ('joule_per_cubic_metre', 'energy_density', '\mathrm{J}/\mathrm{m}^{3}', '{"en-us": "Joule per cubic meter", "en-uk": "Joule per cubic metre"}',
   1, 0, 1, 'SI'),
  ('volt_per_metre', 'electric_field_strength', '\mathrm{V}/\mathrm{m}', '{"en-us": "Volt per meter", "en-uk": "Volt per metre"}',
   1, 0, 1, 'SI'),
  ('coulomb_per_cubic_metre', 'charge_density', '\mathrm{C}/\mathrm{m}^{3}', '{"en-us": "Coulomb per cubic meter", "en-uk": "Coulomb per cubic metre"}',
   1, 0, 1, 'SI'),
  ('coulomb_per_square_metre', 'surface_charge_density', '\mathrm{C}/\mathrm{m}^{2}', '{"en-us": "Coulomb per square meter", "en-uk": "Coulomb per square metre"}',
   1, 0, 1, 'SI'),
  ('farad_per_metre', 'permittivity', '\mathrm{F}/\mathrm{m}', '{"en-us": "Farad per meter", "en-uk": "Farad per metre"}',
   1, 0, 1, 'SI'),
  ('henry_per_metre', 'permeability', '\mathrm{H}/\mathrm{m}', '{"en-us": "Henry per meter", "en-uk": "Henry per metre"}',
   1, 0, 1, 'SI'),
  ('joule_per_mole', 'molar_energy', '\mathrm{J}/\mathrm{mol}', '{"en-us": "Joule per mole"}',
   1, 0, 1, 'SI'),
  ('joule_per_mole_kelvin', 'molar_entropy', '\mathrm{J}/(\mathrm{mol}\cdot\mathrm{K})', '{"en-us": "Joule per mole-kelvin"}',
   1, 0, 1, 'SI'),
  ('coulomb_per_kilogram', 'exposure', '\mathrm{C}/\mathrm{kg}', '{"en-us": "Coulomb per kilogram"}',
   1, 0, 1, 'SI'),
  ('gray_per_second', 'absorbed_dose_rate', '\mathrm{Gy}/\mathrm{s}', '{"en-us": "Gray per second"}',
   1, 0, 1, 'SI'),
  ('watt_per_steradian', 'radiant_intensity', '\mathrm{W}/\mathrm{sr}', '{"en-us": "Watt per steradian"}',
   1, 0, 1, 'SI'),
  ('watt_per_square_metre_steradian', 'radiance', '\mathrm{W}/(\mathrm{m}^{2}\cdot\mathrm{sr})', '{"en-us": "Watt per square meter-steradian", "en-uk": "Watt per square metre-steradian"}',
   1, 0, 1, 'SI'),
  ('katal_per_cubic_metre', 'catalytic_activity_concentration', '\mathrm{kat}/\mathrm{m}^{3}', '{"en-us": "Katal per cubic meter", "en-uk": "Katal per cubic metre"}',
   1, 0, 1, 'SI'),
  ('minute', 'period', '\mathrm{min}', '{"en-us": "Minute"}',
   60, 0, 0, NULL),
  ('hour', 'period', '\mathrm{h}', '{"en-us": "Hour"}',
   3600, 0, 0, NULL),
  ('day', 'period', '\mathrm{d}', '{"en-us": "Day"}',
   86400, 0, 0, NULL),
  ('astronomical_unit', 'length', '\mathrm{au}', '{"en-us": "Astronomical unit"}',
   149597870700, 0, 0, NULL),
  ('degree', 'angle', '{}^{\circ}', '{"en-us": "Degree"}',
   0.017453292519943295, 0, 0, NULL),
  ('hectare', 'area', '\mathrm{ha}', '{"en-us": "Hectare"}',
   10000, 0, 0, NULL),
  ('litre', 'volume', '\mathrm{L}', '{"en-us": "Litre"}',
   0.001, 0, 0, NULL),
  ('tonne', 'mass', '\mathrm{t}', '{"en-us": "Tonne"}',
   1000, 0, 0, NULL),
  ('dalton', 'mass', '\mathrm{Da}', '{"en-us": "Dalton"}',
   1.66053906892e-27, 0, 0, NULL),
  ('electronvolt', 'energy', '\mathrm{eV}', '{"en-us": "Electronvolt"}',
   1.602176634e-19, 0, 0, NULL),
  ('neper', 'angle', '\mathrm{Np}', '{"en-us": "Neper"}',
   1, 0, 0, NULL),
  ('bel', 'angle', '\mathrm{B}', '{"en-us": "Bel"}',
   1, 0, 0, NULL),
  ('decibel', 'angle', '\mathrm{dB}', '{"en-us": "Decibel"}',
   0.1, 0, 0, NULL),
  ('arcminute', 'angle', '{}^{\prime}', '{"en-us": "Arcminute"}',
   0.0002908882086657216, 0, 0, NULL),
  ('arcsecond', 'angle', '{}^{\prime\prime}', '{"en-us": "Arcsecond"}',
   4.84813681109536e-06, 0, 0, NULL)
;

-- ============================================================
-- Update existing variables' si_unit
-- ============================================================
UPDATE variables SET si_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'energy' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "pascal", "exponent": 1}]' WHERE id = 'pressure' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "cubic_metre", "exponent": 1}]' WHERE id = 'volume' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "metre_per_second", "exponent": 1}]' WHERE id = 'velocity' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "metre_per_second_sq", "exponent": 1}]' WHERE id = 'acceleration' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'work' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'heat' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "joule", "exponent": 1}]' WHERE id = 'internal_energy' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "joule", "exponent": 1}, {"unit": "mole", "exponent": -1}, {"unit": "kelvin", "exponent": -1}]' WHERE id = 'gas_constant' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "mole", "exponent": 1}]' WHERE id = 'amount' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "kilogram", "exponent": 1}, {"unit": "metre", "exponent": 1}, {"unit": "second", "exponent": -1}]' WHERE id = 'momentum' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "ampere", "exponent": 1}]' WHERE id = 'electric_current' AND si_unit IS NULL;
UPDATE variables SET si_unit = '[{"unit": "candela", "exponent": 1}]' WHERE id = 'luminous_intensity' AND si_unit IS NULL;
